// Generated by CoffeeScript 1.9.2
(function() {
  'use strict';
  angular.module('HueThesis').controller('LightsIndexCtrl', function($scope, $hue) {
    $scope.lights = $hue.lights().then(function(lights) {
      console.log(lights);
      return $scope.lights = lights;
    });
    $scope.sync = function() {
      $scope.lights = [];
      return $hue.sync().lights().then(function(lights) {
        return $scope.lights = lights;
      });
    };
    return $scope.getStyleFromState = function(state) {
      var k, payload, rgb, v;
      payload = {
        x: state.xy[0],
        y: state.xy[1],
        bri: state.bri / 255
      };
      rgb = $hue.xyBriToRgb(payload);
      for (k in rgb) {
        v = rgb[k];
        rgb[k] = Math.round(255 * v);
      }
      return {
        'background-color': "rgb(" + rgb.r + "," + rgb.g + "," + rgb.b + ")"
      };
    };
  });

}).call(this);
