// Generated by CoffeeScript 1.9.2
(function() {
  angular.module('HueThesis').controller('SongController', function(_, $rootScope, $scope, $interval, Echonest, $visualizer, $spotify) {
    var HVOB;
    $scope.history = [];
    $rootScope.$on('song:set', function(e, song) {
      console.log(arguments);
      return $scope.song = song;
    });
    $rootScope.$on('song:event', function(e, data) {
      return $scope.history.unshift(data);
    });
    HVOB = "ARPDAZA13A6C1557F5";
    return Echonest.songs.search({
      artist: "HVOB",
      title: "Last Song"
    }).then(function(songs) {
      var song;
      if (songs.length === 1) {
        song = songs[0];
        return Echonest.songs.get({
          id: song.id,
          bucket: ['id:spotify', 'tracks', 'audio_summary']
        }).then(function(song) {
          console.log(song);
          return $visualizer.set({
            title: song.title,
            artist: song.artist_name,
            spotifyId: song.tracks[0].foreign_id,
            analysis: song.audio_summary
          });
        });
      }
    });
  });

}).call(this);
