// Generated by CoffeeScript 1.9.2
(function() {
  var VisualizerService;

  angular.module('HueThesis').service('$visualizer', VisualizerService = (function() {
    function VisualizerService($rootScope) {
      this.get = function() {
        return this.song;
      };
      this.set = function(song) {
        $rootScope.$emit('song:set', song);
        return this.song = song;
      };
    }

    return VisualizerService;

  })());

}).call(this);
