// Generated by CoffeeScript 1.9.2
(function() {
  angular.module('HueThesis', ['ionic', 'ngCordova', 'ngResource', 'angular-echonest']).run(function($rootScope, $ionicPlatform, $hue) {
    return $ionicPlatform.ready(function() {});
  }).config(function(EchonestProvider, $httpProvider, $stateProvider, $urlRouterProvider) {
    EchonestProvider.setApiKey('YSSOAU0PJYAK6WUYD');
    $stateProvider.state('app', {
      url: '/app',
      abstract: true,
      templateUrl: 'templates/main.html',
      controller: 'MainController'
    }).state('app.home', {
      url: '/home',
      cache: true,
      views: {
        'viewContent': {
          templateUrl: 'templates/views/home.html',
          controller: 'HomeController'
        }
      }
    }).state('app.settings', {
      url: '/settings',
      cache: true,
      views: {
        'viewContent': {
          templateUrl: 'templates/views/settings.html',
          controller: 'SettingsController'
        }
      }
    }).state('app.canvas', {
      url: '/canvas',
      cache: true,
      views: {
        'viewContent': {
          templateUrl: 'templates/views/canvas.html',
          controller: 'CanvasController'
        }
      }
    }).state('app.song', {
      url: '/song',
      cache: true,
      views: {
        'viewContent': {
          templateUrl: 'templates/views/song.html',
          controller: 'SongController'
        }
      }
    }).state('app.lights', {
      url: '/lights',
      cache: true,
      views: {
        'viewContent': {
          templateUrl: 'templates/views/lights.html',
          controller: 'LightsController'
        }
      }
    });
    return $urlRouterProvider.otherwise('/app/home');
  });

}).call(this);

//# sourceMappingURL=app.js.map
