// Generated by CoffeeScript 1.9.2
(function() {
  angular.module('HueThesis', ['ionic', 'ngCordova', 'ngResource']).run(function($ionicPlatform) {
    return $ionicPlatform.ready(function() {});
  }).config(function($httpProvider, $stateProvider, $urlRouterProvider) {
    $stateProvider.state('app', {
      url: '/app',
      abstract: true,
      templateUrl: 'templates/main.html',
      controller: 'MainController'
    }).state('app.home', {
      url: '/home',
      cache: true,
      views: {
        'viewContent': {
          templateUrl: 'templates/views/home.html',
          controller: 'HomeController'
        }
      }
    }).state('app.settings', {
      url: '/settings',
      cache: true,
      views: {
        'viewContent': {
          templateUrl: 'templates/views/settings.html',
          controller: 'SettingsController'
        }
      }
    }).state('app.lights', {
      url: '/lights',
      cache: true,
      views: {
        'viewContent': {
          templateUrl: 'templates/views/lights.html',
          controller: 'LightsController'
        }
      }
    });
    return $urlRouterProvider.otherwise('/app/home');
  });

}).call(this);
